#!/bin/sh

# Install Nix
sh <(curl -L https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume

# Install Packages
nix-env -iA \
  nixpkgs.antibody \
  nixpkgs.fzf \
  nixpkgs.hub \
  nixpkgs.libmysqlclient \
  nixpkgs.neovim \
  nixpkgs.ripgrep \
  nixpkgs.stow \
  nixpkgs.slack-cli \
  nixpkgs.tree \
  nixpkgs.tmux \
  nixpkgs.watch \
  nixpkgs.yarn \
  nixpkgs.argo

# Stow
stow alacritty
stow git
stow nvim
stow tmux
stow zsh

# Bundle zsh plugins
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
